repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort --settings-file ./pyproject.toml --profile black --filter-files .
        language: system
        types: [ python ]
        pass_filenames: false

      - id: black
        name: black
        entry: black --config ./pyproject.toml .
        language: system
        types: [ python ]
        pass_filenames: false

      - id: flake8
        name: flake8
        entry: flake8 --config ./pyproject.toml
        language: system
        types: [ python ]
        pass_filenames: false

  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v2.4.0
    hooks:
        - id: end-of-file-fixer
        - id: check-byte-order-marker

  - repo: 'https://github.com/pre-commit/mirrors-mypy'
    rev: v1.7.1
    hooks:
      - id: mypy
        files: ^Bin/
        args: ["--config-file", "./pyproject.toml"]
