from .template import *
from src.styles import Stylesheet


POP_CLOSE_BUTTON_STYLESHEET = Stylesheet(CLOSE_BUTTON_STYLESHEET_TEMPLATE)
POP_CLOSE_BUTTON_STYLESHEET_HOVER = Stylesheet(CLOSE_BUTTON_STYLESHEET_TEMPLATE_HOVER)
