from .template import *
from src.styles import Stylesheet


POP_UP_CLOSE_BUTTON_STYLESHEET = Stylesheet(POP_UP_CLOSE_BUTTON_STYLESHEET_TEMPLATE)
POP_UP_CLOSE_BUTTON_STYLESHEET_HOVER = Stylesheet(POP_UP_CLOSE_BUTTON_STYLESHEET_TEMPLATE_HOVER)
