from .template import *
from src.styles import stylesheet


POP_UP_CLOSE_BUTTON_STYLESHEET = stylesheet(POP_UP_CLOSE_BUTTON_STYLESHEET_TEMPLATE)
POP_UP_CLOSE_BUTTON_STYLESHEET_HOVER = stylesheet(POP_UP_CLOSE_BUTTON_STYLESHEET_TEMPLATE_HOVER)
