from .template import *
from src.styles import Stylesheet


LEFT_MENU_BUTTON_STYLESHEET = Stylesheet(LEFT_MENU_BUTTON_STYLESHEET_TEMPLATE)
LEFT_MENU_BUTTON_STYLESHEET_HOVER = Stylesheet(LEFT_MENU_BUTTON_STYLESHEET_TEMPLATE_HOVER)
